---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre-web
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: calibre-web
      version: 8.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    podSecurityContext:
      supplementalGroups:
        - 568
        - 1001
        - 65539

    image:
      repository: ghcr.io/linuxserver/calibre-web
      tag: 0.6.19

    env:
      TZ: ${TZ}
      PGID: 65539
      DOCKER_MODS: "linuxserver/calibre-web:calibre"

    persistence:
      config:
        enabled: true
        existingClaim: calibre-web-config
      media:
        enabled: true
        existingClaim: media-nfs
        mountPath: /media

    ingress:
      main:
        primary: true
        enabled: true
        ingressClassName: "traefik"
        annotations:
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          external-dns.alpha.kubernetes.io/target: "${SECRET_CLOUDFLARE_TUNNEL_ID_2}.cfargotunnel.com"
        hosts:
          - host: "calibre-web.${SECRET_DOMAIN_CASA}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "calibre-web.${SECRET_DOMAIN_CASA}"
      secondary:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          external-dns.alpha.kubernetes.io/target: "${SECRET_CLOUDFLARE_TUNNEL_ID_2}.cfargotunnel.com"
        hosts:
          - host: "calibre-web.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "calibre-web.${SECRET_DOMAIN}"


    resources:
      requests:
        memory: 256Mi
      limits:
        memory: 512Mi
