---

- name: Set hostname to inventory hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  when:
  - ansible_hostname != inventory_hostname

- name: Check for bridge-nf-call-iptables
  ansible.builtin.stat:
    path: /proc/sys/net/bridge/bridge-nf-call-iptables
  register: bridge_nf_call_iptables_result

- name: Disable IPv6
  ansible.builtin.blockinfile:
    path: /etc/sysctl.d/99-ipv6-disable.conf
    mode: 0644
    create: true
    block: |
      net.ipv6.conf.all.disable_ipv6 = 1
      net.ipv6.conf.default.disable_ipv6 = 1
      net.ipv6.conf.lo.disable_ipv6 = 1
  when:
  - bridge_nf_call_iptables_result.stat.exists
  register: sysctl_network

- name: Set Kubernetes network configuration
  ansible.builtin.blockinfile:
    path: /etc/sysctl.d/99-kubernetes-cri.conf
    mode: 0644
    create: true
    block: |
      net.ipv4.ip_forward = 1
      net.bridge.bridge-nf-call-iptables = 1
  when:
  - bridge_nf_call_iptables_result.stat.exists
  register: sysctl_network

- name: Reload Kubernetes network configuration
  ansible.builtin.shell: sysctl -p /etc/sysctl.d/99-kubernetes-cri.conf && sysctl -p /etc/sysctl.d/99-ipv6-disable.conf
  when:
  - sysctl_network.changed
  - bridge_nf_call_iptables_result.stat.exists
