---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: global-vars
data:
  CLUSTER_NAME: "homelab-talos-0"
  CLUSTER_ID: "1"
  CLUSTER_APISERVER_ENDPOINT: "10.250.2.254"
  CLUSTER_CIDR: "10.244.0.0/16"
  METALLB_RANGE: "10.250.13.1-10.250.14.250"
  CILIUM_BGP_LB_RANGE: "10.250.13.1-10.250.14.250"
  SERVICE_CIDR: "10.96.0.0/12"
  HOMELAB_VLAN_CIDR: "10.250.0.1/20"
  GATEWAY_ADDRESS: "10.250.0.1"
  TRUENAS_VM_ADDRESS: "10.250.0.200"
  BLUEIRIS_ADDRESS: "10.250.0.202"
  SVC_K8S_GATEWAY_ADDR: "10.250.13.53"
  SVC_JELLYFIN_ADDR: "10.250.14.105"
  SVC_MOSQUITTO_ADDR: "10.250.14.107"
  SVC_DIZQUETV_ADDR: "10.250.14.106"
  SVC_UNIFI_ADDR: "10.250.14.117"
  SVC_TRAEFIK_ADDRESS: "10.250.13.100"
  SVC_CILIUM_INGRESS_ADDRESS: "10.250.14.100"
  SVC_PLEX_ADDR: "10.250.13.190"
  SVC_QBITTORRENT_ADDR: "10.250.14.110"  # needs port-forward
  SVC_SMTP_RELAY_ADDR: "10.250.14.203"
  SVC_MAILQTT_ADDR: "10.250.14.225"
  SVC_HASS_ADDRESS: "10.250.14.3"
  SVC_SYSLOG_ADDR: "10.250.14.200"
  SVC_POSTGRES_ADDR: "10.250.14.54"
  SVC_SYNCTHING_ADDR: "10.250.14.10"
  CAM1_IP: "10.249.250.2"
  CAM2_IP: "10.249.250.3"
  CAM3_IP: "10.249.250.4"
  CAM4_IP: "10.249.250.5"
