---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-settings
data:
  GATEWAY_ADDRESS: "10.250.0.1"
  STORAGE_ADDRESS: "10.250.1.100"
  KUBE_VIP_ADDRESS: "10.250.14.200"
  KUBE_VIP_INTERFACE: "ens1"
  SVC_BLOCKY_ADDRESS: "10.250.14.112"
  SVC_JELLYFIN_ADDR: "10.250.14.105"
  SVC_DIZQUETV_ADDR: "10.250.14.106"
  SVC_UNIFI_ADDR: "10.250.14.117"
  SVC_TRAEFIK_ADDRESS: "10.250.14.100"
  SVC_TRAEFIK_PUBLIC_ADDRESS: "10.250.14.101" # needs port-forward
  SVC_WIREGUARD: "10.250.14.102"
