---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-settings
data:
  CLUSTER_CIDR: "10.42.0.0/16"
  SERVICE_CIDR: "10.43.0.0/16"
  HOMELAB_VLAN_CIDR: "10.250.0.1/20"
  GATEWAY_ADDRESS: "10.250.0.1"
  QNAP_ADDRESS: "192.168.2.19"
  OC200_ADDRESS: "192.168.1.76"
  KUBE_VIP_ADDRESS: "10.250.14.200"
  METALLB_RANGE: "10.250.14.1-10.250.14.199"
  TRUENAS_ADDRESS: "10.250.1.100"
  TRUENAS_VM_ADDRESS: "10.250.0.200"
  TRUENAS_NGINX_ADDRESS: "10.250.1.99"
  TRUENAS_NZBGET_ADDRESS: "10.250.1.97"
  TRUENAS_MINIO_ADDRESS: "10.250.1.90"
  SVC_BLOCKY_ADDRESS: "10.250.14.112"
  SVC_JELLYFIN_ADDR: "10.250.14.105"
  SVC_MOSQUITTO_ADDR: "10.250.14.107"
  SVC_DIZQUETV_ADDR: "10.250.14.106"
  SVC_UNIFI_ADDR: "10.250.14.117"
  SVC_OMADA_ADDRESS: "10.250.14.127"
  SVC_TRAEFIK_ADDRESS: "10.250.14.100"
  SVC_PLEX_ADDR: "10.250.14.190"
  SVC_QBITTORRENT_ADDR: "10.250.14.110"  # needs port-forward
  CAM1_IP: "192.168.1.221"
