---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-config-v1
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ceph-block
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-config-0
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block-ec
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-downloads-v5
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
  storageClassName: rook-cephfs-fast-low-redundancy
