---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: networking
spec:
  interval: 5m
  releaseName: cloudflared
  chart:
    spec:
      # renovate: registryUrl=https://xunholy.github.io/charts
      chart: cloudflared
      version: 0.1.2
      sourceRef:
        kind: HelmRepository
        name: xunholy-charts
        namespace: flux-system
      interval: 5m
  values:
    replicaCount: 3
    image:
      repository: raspbernetes/cloudflared
      tag: "2022.7.1"
    cloudflared:
      # Tunnel ID should be unique per instance of running cloudflared
      tunnelID: "${SECRET_CLOUDFLARE_TUNNEL_ID_1}"
      # This is a reference to an existing secret containing the credentials;
      existingSecret: cloudflared-credentials
      # Ingress hosts are directly copied into the configmap;
      # Read: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/configuration-file/ingress
      ingress:
        - hostname: "k8sapi.${SECRET_DOMAIN_CASA}"
          service: tcp://kubernetes.default:443
          originRequest:
            proxyType: socks
        - hostname: "bastion.${SECRET_DOMAIN_CASA}"
          service: bastion
        - hostname: "*.${SECRET_DOMAIN_CASA}"
          service: https://traefik.networking
          originRequest:
            noTLSVerify: true
        - hostname: "*.${SECRET_DOMAIN}"
          service: https://traefik.networking
          originRequest:
            noTLSVerify: true
        - service: http_status:404
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - cloudflared
              topologyKey: kubernetes.io/hostname
