---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: zigbee2mqtt
      version: 9.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    disableWait: true
    remediation:
      retries: 100
    createNamespace: true
  upgrade:
    remediation:
      retries: 100
  dependsOn:
    - name: mosquitto
      namespace: home
  values:
    image:
      repository: ghcr.io/koenkk/zigbee2mqtt
      tag: 1.25.2
    env:
      TZ: "${TZ}"
      ZIGBEE2MQTT_DATA: /data
      ZIGBEE2MQTT_CONFIG_MQTT_USER: "${MQTT_USER}"
      ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: "${MQTT_PASSWORD}"
    ingress:
      main:
        enabled: true
        primary: true
        ingressClassName: "traefik"
        annotations:
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          external-dns.alpha.kubernetes.io/target: "${SECRET_CLOUDFLARE_TUNNEL_ID_1}.cfargotunnel.com"
        hosts:
          - host: "zigbee2mqtt.${SECRET_DOMAIN_CASA}"
            paths:
              - path: /
                pathType: Prefix
          - host: "zigbee2mqtt.${SECRET_DOMAIN_CASA}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "zigbee2mqtt.${SECRET_DOMAIN_CASA}"
    persistence:
      config:
        enabled: true
        existingClaim: zigbee2mqtt-config-v2
        mountPath: "/data"
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_c46794596029ec11b42d6c7840c9ce8d-if00-port0
    nodeSelector:
      kubernetes.io/hostname: nuc1
    securityContext:
      privileged: true
    podSecurityContext:
      supplementalGroups:
        - 20 # dialout for /dev/ttyUSB0
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 500Mi
    config:
      # Minimal configuration.yml example
      permit_join: true
      homeassistant: true
      mqtt:
        server: mqtt://mosquitto:1883
      serial:
        port: /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_c46794596029ec11b42d6c7840c9ce8d-if00-port0
      frontend:
        port: 8080
