---
apiVersion: v1
kind: ConfigMap
metadata:
  name: plex-trakt-sync-config
  namespace: media
data:
  config.json: |
    {
        "log_debug_messages": false,
        "logging": {
            "append": false
        },
        "cache": {
            "path": "$PTS_CACHE_DIR/trakt_cache"
        },
        "sync": {
            "trakt_to_plex": {
                "watched_status": true,
                "ratings": true,
                "liked_lists": true,
                "watchlist": true
            },
            "plex_to_trakt": {
                "watched_status": true,
                "ratings": true,
                "collection": true
            }
        },
        "watch": {
            "username_filter": false
        },
        "xbmc-providers": {
            "movies": "imdb",
            "shows": "tvdb"
        },
        "excluded-libraries": [
        ]
    }
---
apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: media
  name: plex-trakt-sync
spec:
  schedule: "15 */4 * * *"
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      backoffLimit: 3
      ttlSecondsAfterFinished: 300
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: trakt-sync
              image: ghcr.io/taxel/plextraktsync:0.20.2
              volumeMounts:
                - mountPath: /app/config/config.json
                  name: config
                  subPath: config.json
                - mountPath: /app/config/.pytrakt.json
                  name: pytrakt-json
                  subPath: .pytrakt.json
              envFrom:
                - secretRef:
                    name: plex-trakt-sync-env
          volumes:
            - name: config
              configMap:
                name: plex-trakt-sync-config
            - name: pytrakt-json
              secret:
                secretName: plex-trakt-sync-pytrakt-json
