---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  install:
    disableWait: true
    remediation:
      retries: 100
  upgrade:
    remediation:
      retries: 100
  chart:
    spec:
      chart: app-template
      version: 1.1.3
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 15m
  values:
    image:
      repository: ghcr.io/onedr0p/qbittorrent
      tag: 4.4.5@sha256:6765f8a7709ad446fb761d3dde16f2a2706d118c21e2f191955ba07935e75e29

    podAnnotations:
      setGateway: "true"
      k8s.v1.cni.cncf.io/networks: plex-wifi-static

    env:
      TZ: "${TZ}"
      UMASK: "022"
      QBITTORRENT__PORT: &port 8080

    service:
      main:
        ports:
          http:
            port: *port
      bittorrent:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: "${SVC_QBITTORRENT_ADDR}"
        externalIPs:
          - "${SVC_QBITTORRENT_ADDR}"
        ports:
          bittorrent:
            enabled: true
            port: 50413
            protocol: TCP
            targetPort: 50413
        externalTrafficPolicy: Local

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          external-dns.alpha.kubernetes.io/target: "${SECRET_CLOUDFLARE_TUNNEL_ID_2}.cfargotunnel.com"
        hosts:
          - host: &host "qbittorrent.${SECRET_DOMAIN_CASA}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

#    TODO for config as code
#    initContainers:
#      copy-config:
#        image: busybox:latest@sha256:ad9bd57a3a57cc95515c537b89aaa69d83a6df54c4050fcf2b41ad367bec0cd5
#        command:
#          - "/bin/sh"
#          - -c
#        args:
#          - cp /data/configfiles/* /data/config/
#        volumeMounts:
#          - name: config
#            mountPath: /data/config
#          - name: configfiles
#            mountPath: /data/configfiles

    metrics:
      enabled: true
      exporter:
        image:
          repository: ghcr.io/k8s-at-home/prometheus-qbittorrent-exporter
          tag: v1.2.0
      serviceMonitor:
        interval: 1m
        scrapeTimeout: 10s
      prometheusRule:
        enabled: true

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 65539

    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent-config-v1

      cache:
        enabled: true
        type: emptyDir
        mountPath: /config/qBittorrent/cache

      media:
        enabled: true
        existingClaim: media-nfs
        mountPath: /media

      restore:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${TRUENAS_VM_ADDRESS}"
            path: /mnt/tank/backups/softwarrself/qbittorrent
        mountPath: /backup
        readOnly: false

    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 6Gi
