---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - angelnu.yaml
  - bitnami-charts.yaml
  - blakeshome-charts.yaml
  - coredns-charts.yaml
  - deliveryhero-charts.yaml
  - grafana-charts.yaml
  - giantswarm-charts.yaml
  - hashicorp-charts.yaml
  - infracloudio-charts.yaml
  - ingress-nginx-charts.yaml
  - jetstack-charts.yaml
  - k8s-at-home-charts.yaml
  - falco-security-charts.yaml
  - kubernetes-sigs-descheduler-charts.yaml
  - lwolf-charts.yaml
  - nfs-subdir-external-provisioner-charts.yaml
  - node-feature-discovery-charts.yaml
  - prometheus-community-charts.yaml
  - stakater-charts.yaml
  - traefik-charts.yaml
  - victoriametrics-charts.yaml
  - rook-ceph-charts.yaml
  - charlie-haley-charts.yaml
  - metrics-server-charts.yaml
  - metallb-charts.yaml
  - xunholy-charts.yaml
  - cilium-charts.yaml
  - linkerd-charts.yaml
  - kubernetes-replicator-charts.yaml
  - kyverno-charts.yaml
  - k8s-gateway-charts.yaml
  - bjw-s.yaml
  - robusta.yaml
  - intel.yaml
  - external-secrets.yaml
  - weave-gitops.yaml
  - tf-controller.yaml
  - piraeus.yaml
  - external-dns.yaml
  - cloudnative-pg.yaml
  - backube.yaml
