---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: calibre
      version: 5.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:


    podSecurityContext:
      supplementalGroups:
        - 568

    image:
      repository: ghcr.io/linuxserver/calibre
      tag: 5.44.0

    podAnnotations:
      backup.velero.io/backup-volumes: config

    env:
      TZ: ${TZ}
      PGID: 65539

    persistence:
      config:
        enabled: true
        existingClaim: calibre-config
      media:
        enabled: true
        existingClaim: media-nfs
        mountPath: /media
#      nzbget-downloads:
#        enabled: true
#        type: custom
#        volumeSpec:
#          nfs:
#            server: "${TRUENAS_VM_ADDRESS}"
#            path: /mnt/nvme/nzbget-downloads
#        mountPath: /nzbget-downloads

    service:
      webserver:
        enabled: true

    ingress:
      main:
        primary: true
        enabled: true
        ingressClassName: "traefik"
        annotations:
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          external-dns.alpha.kubernetes.io/target: "${SECRET_CLOUDFLARE_TUNNEL_ID_1}.cfargotunnel.com"
        hosts:
          - host: "calibre.${SECRET_DOMAIN_CASA}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "calibre.${SECRET_DOMAIN_CASA}"

    resources:
      requests:
        cpu: 0.003
        memory: 1Gi
      limits:
        memory: 10Gi
