---

# https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/
# https://github.com/PyratLabs/ansible-role-k3s#server-control-plane-configuration

# Define the host as control plane nodes
k3s_control_node: true

# k3s settings for all control-plane nodes
k3s_server:
  node-ip: "{{ ansible_host }}"
  tls-san:
  - "{{ k3s_registration_address }}"
  docker: false
  disable:
  - traefik
  - servicelb
  - metrics-server
  - local-storage
  disable-network-policy: true
  disable-cloud-controller: true
  write-kubeconfig-mode: "644"
  # CIDR for pod IPs
  cluster-cidr: "10.42.0.0/16"
  # CIDR for service IPs
  service-cidr: "10.43.0.0/16"
  kubelet-arg:
  - "feature-gates=GracefulNodeShutdown=true,MixedProtocolLBService=true"
