---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - _pvc
  - bazarr
  - dizquetv
  - overseerr
  - jellyfin
  - prowlarr
  - radarr
  - readarr
  - readarr-audiobooks
  - sonarr
  - tautulli
  - qbittorrent
  - plex
  - arr-misc
  - calibre
  - calibre-web
  - mylar
  - tdarr
  - sabnzbd
  - plex-meta-manager
