---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- _pvc
- _external_svc
- bazarr
- dizquetv
- nzbget
- overseerr
- jellyfin
# - plex
- prowlarr
# - qbittorrent
- radarr
- readarr
- readarr-audiobooks
# - resilio
- sonarr
- tautulli
- calibre
- calibre-web
