---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
#  - ./frigate/ks.yaml
  - ./home-assistant/ks.yaml
  - ./mailqtt/ks.yaml
  - ./mosquitto/ks.yaml
  - ./smtp-relay/ks.yaml
  - ./syncthing/ks.yaml
#  - ./zigbee2mqtt/ks.yaml
