---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: plex
      version: 6.3.4
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    disableWait: true
    remediation:
      retries: 100
  upgrade:
    remediation:
      retries: 100
  values:
    tolerations:
      - key: "nuc"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    image:
      repository: ghcr.io/k8s-at-home/plex
      tag: v1.27.1.5916-6b0e31a64
    env:
      TZ: "${TZ}"
    podSecurityContext:
      supplementalGroups:
        - 44
        - 109
        - 100
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${SVC_PLEX_ADDR}
        externalIPs:
          - "${SVC_PLEX_ADDR}"
        externalTrafficPolicy: Local
    podAnnotations:
      k8s.v1.cni.cncf.io/networks: plex-wifi-static
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          external-dns.alpha.kubernetes.io/target: "${SECRET_CLOUDFLARE_TUNNEL_ID_2}.cfargotunnel.com"
        hosts:
          - host: "plex.${SECRET_DOMAIN_CASA}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "plex.${SECRET_DOMAIN_CASA}"
    persistence:
      config:
        enabled: true
        existingClaim: plex-library-config-v1
      media:
        enabled: true
        existingClaim: media-nfs
        mountPath: /data
      transcode:
        enabled: true
        type: emptyDir
        medium: Memory
      backup:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${TRUENAS_VM_ADDRESS}"
            path: /mnt/tank/backups/softwarrself/plex
        mountPath: /config/Backups
        readOnly: false
    resources:
      requests:
        cpu: 200m
        memory: 2Gi
        gpu.intel.com/i915: 1
      limits:
        gpu.intel.com/i915: 1

    addons:
      promtail:
        enabled: true
        image:
          repository: ghcr.io/k8s-at-home/promtail
          tag: v2.6.1
        loki: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
        logs:
          - name: promtail/plex
            path: "/config/Library/Application Support/Plex Media Server/Logs/*.log"
          - name: promtail/plex/plugins
            path: "/config/Library/Application Support/Plex Media Server/Logs/PMS Plugin Logs/*.log"
        volumeMounts:
          - name: config
            mountPath: /config
            readOnly: true
        securityContext:
          runAsUser: 0
