---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: backup
spec:
  interval: 5m
  install:
    disableWait: true
    remediation:
      retries: 30
  upgrade:
    remediation:
      retries: 30
  chart:
    spec:
      # renovate: registryUrl=https://vmware-tanzu.github.io/helm-charts
      chart: velero
      version: 2.29.8
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu-charts
        namespace: flux-system
      interval: 5m
  values:
    deployRestic: true
    restic:
      podVolumePath: /var/lib/kubelet/pods
      privileged: true
      resources:
        requests:
          memory: 200Mi
          cpu: 15m
        limits:
          memory: 3000Mi
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.4.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
    serviceMonitor:
      enabled: true
    configuration:
      provider: aws
      extraEnvVars:
        TZ: "${TZ}"
      backupStorageLocation:
        name: aws
        default: true
        provider: velero.io/aws
        bucket: velero
        config:
          region: eu-central-1
          # s3ForcePathStyle: true
          s3Url: https://s3.eu-central-1.wasabisys.com
          # publicUrl: "https://s3.${SECRET_DOMAIN_CASA}"
          signatureVersion: "1"
          profile: "default"
    credentials:
      existingSecret: s3-credentials
    schedules:
      backup-s3:
        disabled: false
        schedule: "10 6 * * 0"
        useOwnerReferencesInBackup: true
        template:
          ttl: "336h"
