---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cert-manager.yaml
- flux-system.yaml
- home.yaml
- longhorn-system.yaml
- metallb-system.yaml
- kube-system.yaml
- media.yaml
- monitoring.yaml
- networking.yaml
- backup.yaml
- linkerd.yaml
- tools.yaml
