---
kubernetes:
  children:
    master:
      hosts:
        nuc1:
          ansible_host: "10.250.1.101"
          ansible_user: "runtime"
          ansible_ssh_private_key_file: ~/.ssh/dragos
        nuc2:
          ansible_host: "10.250.1.102"
          ansible_user: "runtime"
          ansible_ssh_private_key_file: ~/.ssh/dragos

    worker:
      hosts: {}
    #     k8s-3:
    #     k8s-4:
    #     k8s-5:
