---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd
  namespace: linkerd
spec:
  interval: 5m
  chart:
    spec:
      chart: linkerd2
      version: 2.11.2
      sourceRef:
        kind: HelmRepository
        name: linkerd-charts
        namespace: flux-system
  timeout: 10m0s
  # dependsOn:
  #   - name: linkerd-crds
  #     namespace: flux-system
  values:
    identity:
      issuer:
        crtExpiry: "2023-06-12T10:55:02Z"
    installNamespace: false
    enableEndpointSlices: true
    policyController:
      resources:
        cpu:
          request: 10m
        memory:
          limit: 50Mi
          request: 10Mi
    proxy:
      cores: 0
      resources:
        cpu:
          request: 10m
        memory:
          limit: 50Mi
          request: 10Mi
    proxyInit:
      resources:
        cpu:
          request: 10m
        memory:
          limit: 50Mi
          request: 10Mi
  valuesFrom:
    - kind: Secret
      name: linkerd-certs
      valuesKey: ca.crt
      targetPath: identityTrustAnchorsPEM
      optional: false
    - kind: Secret
      name: linkerd-certs
      valuesKey: issuer.crt
      targetPath: identity.issuer.tls.crtPEM
      optional: false
    - kind: Secret
      name: linkerd-certs
      valuesKey: issuer.key
      targetPath: identity.issuer.tls.keyPEM
      optional: false
